feat: added ip addresses to agent data source
thousandeyes/terraform-provider-thousandeyes pull request #150
Opened 2023-12-05 14:41 UTC by joaomper-TE

As requested within #128 this adds ip addresses to the Agent DataSource:

```
Changes to Outputs:
  + agent_id     = 123213
  + agent_name   = "Vancouver, Canada"
  + ip_addresses = [
      + "155.204.108.19",
      + "155.204.108.16",
      + "155.204.108.15",
      + "155.204.108.17",
      + "155.204.108.18",
      + "155.204.108.9",
      + "155.204.108.10",
      + "155.204.108.11",
      + "155.204.108.8",
      + "155.204.108.6",
      + "155.204.108.7",
      + "155.204.108.12",
      + "2607:f6f0:3400:96::2:7",
      + "2607:f6f0:3400:96::2:4",
      + "2607:f6f0:3400:96::2:3",
      + "2607:f6f0:3400:96::2:5",
      + "2607:f6f0:3400:96::2:6",
      + "2607:f6f0:3400:96::1:6",
      + "2607:f6f0:3400:96::1:7",
      + "2607:f6f0:3400:96::1:8",
      + "2607:f6f0:3400:96::1:5",
      + "2607:f6f0:3400:96::1:3",
      + "2607:f6f0:3400:96::1:4",
      + "2607:f6f0:3400:96::1:9",
    ]
╷
```

2023-12-05 15:08 UTC, pedro-te commented on docs/data-sources/account_group.md
> +    agent_id = 3 # Singapure
It's actually `Singapore` 😄

2023-12-05 15:14 UTC, joaomper-TE commented on docs/data-sources/account_group.md
> +    agent_id = 3 # Singapure
😄 will correct!

2023-12-05 15:59 UTC, joaomper-TE commented
/review @phpinhei-te @brumarqu-te @sfreitas-te @shahid-te @vascmart-te @jabrowne-te

2023-12-05 16:10 UTC, vascmart-te approved these changes

2023-12-05 16:13 UTC, phpinhei-te approved these changes

2023-12-05 16:20 UTC, pedro-te approved these changes

2023-12-06 09:45 UTC, joaomper-TE commented
> i'm not sure but from the referenced issue seems that customer needs the publicIpAddresses.
We need to pull in the IP addresses of agent in Sao-paulo Brazil for example and then allow those IP's on our network firewall

Yeah, that's a fair question. I asked yesterday in the GH issue to make sure which IP Addresses the user is referring to (will only merge this afterwards)

2023-12-06 19:47 UTC, sfreitas-te requested changes
Please add the issue number to the log messages

2023-12-07 11:03 UTC, merged