DOCS-1027 Initial Documentation Updates
thousandeyes/terraform-provider-thousandeyes pull request #79
Opened 2022-07-04 23:13 UTC by tomwizard-eyes

2022-07-06 23:24 UTC, raul-te requested changes
A few changes are required for this to work. You need to update the fields description in `schemas.go`, and then run `go generate`. The CI job configured in this repository is failing because of this.

2022-07-06 23:24 UTC, raul-te commented on docs/resources/agent_to_agent.md
> -- `agents` (Block Set, Min: 1) Agents to use (see [below for nested schema](#nestedblock--agents))
Everything under ` <!-- schema generated by tfplugindocs -->` will be overwritten by `go generate`. These descriptions will need to be changed in [schemas.go](https://github.com/thousandeyes/terraform-provider-thousandeyes/blob/496382e168f660e21f5a640f2632658af043506e/thousandeyes/schemas.go).

2022-07-06 23:24 UTC, raul-te commented on docs/resources/agent_to_server.md
> -- `agents` (Block Set, Min: 1) Agents to use (see [below for nested schema](#nestedblock--agents))
Everything under ` <!-- schema generated by tfplugindocs -->` will be overwritten by `go generate`. These descriptions will need to be changed in [schemas.go](https://github.com/thousandeyes/terraform-provider-thousandeyes/blob/496382e168f660e21f5a640f2632658af043506e/thousandeyes/schemas.go).

2022-07-14 21:58 UTC, tomwizard-eyes commented on thousandeyes/schemas.go
> +		Description:  "[Page Load, HTTP Server, End-to-End (Server), End-to-End (Agent), DNS+ Domain, DNS+ Server, DNS Server, DNS Trace, DNSSEC, Transactions, Web Transactions, BGP, Path Trace, FTP, SIP S
```suggestion
		Description:  "[Page Load, HTTP Server, End-to-End (Server), End-to-End (Agent), DNS Server, DNS Trace, DNSSEC, Transactions, Web Transactions, BGP, Path Trace, FTP, SIP Server] The type of alert rule. Acceptable values include the verbose names of supported tests.",
```

2022-07-14 22:38 UTC, raul-te submitted a review, later dismissed

2022-07-14 22:46 UTC, raul-te approved these changes

2022-07-14 22:46 UTC, merged